### ISSUE TITLE
Client SDK sets unsafe header `content-length`

### ISSUE THREAD

**Issue by sayerhs** [statsig-io/dotnet-sdk#31]
Statsig dotnet package version: 1.17.0

I am using the Statsig package with Blazor WASM app and I see the following error message in the Developer console. I have verified that this error is emitted on outgoing POST requests to `https://statsigapi.net/v1/initialize` URL.

```
Refused to set unsafe header "content-length"
```

**Comment by tore-statsig** [comment]
Thanks for the report.  We have updated the network class since this report, but I never saw us manually setting the content-length header, and we certainly dont now

https://github.com/statsig-io/dotnet-sdk/blob/main/dotnet-statsig/src/Statsig/Network/RequestDispatcher.cs#L81

Please reopen if this is an issue on the latest version.
