### ISSUE TITLE
Feat: Add option for get gate with default value

### ISSUE THREAD

**Issue by jenshenneberg** [statsig-io/dotnet-sdk#33]
I'm working on adding a statsig provider for .net and I am facing the same issue as described for [GO sdk](https://github.com/statsig-io/go-sdk/issues/32) and [Java sdk](https://github.com/statsig-io/java-server-sdk/issues/22)

**Problem**
(Copied from https://github.com/statsig-io/java-server-sdk/issues/22)
BooleanEvaluation with default value true cannot fallback to true.
On scenarios such as get gate of non-existing gate, statsig returns false without indication of whether it was successful get gate or some error reason. Therefore, the evaluation will be evaluated to false in this case.

**Suggested solution**
add:
`public static bool CheckGateSync(StatsigUser user, string gateName, bool fallback)`

**Comment by jenshenneberg** [comment]
@tore-statsig : For some reason this feature request has been closed as completed, but I don't think it has been. Would you mind taking a look?

**Comment by kenny-statsig** [comment]
@jenshenneberg Sorry about that, the issue was auto-closed from our task management integration. 
Though we aren't directly supporting a default return value, the new `GetFeatureGate` API allows you to fallback to a different default value based on the evaluation reason. So in your example, you can check if the evaluation reason is `Unrecognized` and then choose `true`. Hope that makes sense.

**Comment by jenshenneberg** [comment]
@kenny-statsig : Thanks for that. That new API is very helpful and has allowed me to fix the issue in the OpenFeature provider for statsig.
